#!/usr/bin/env bash
# while loop from 1 to 10

DISP_MSG="Best School"

i=1
while [ "$i" -le 10 ]; do
	if [ "$i" -eq 4 ]; then
		echo -e "bad luck"

	elif [ "$i" -eq 8 ]; then
		echo -e "good luck"

	else
		echo -e "$DISP_MSG"

	fi
	i="$((i+1))"
done
